name: Terraform apply workflow

on:
  push: 
    branches: [$default-branch]
  pull_request:
    branches: [$default-branch]
  workflow_dispatch:
      
jobs:
  call-aws-terraform-noinfranchange:
    uses: tikenek/test-workflow/.github/workflows/template2.yml@v1
    secrets:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
