name: Terraform apply workflow

on:
  push: 
    branches: [$default-branch]
  pull_request:
    branches: [$default-branch]
  workflow_dispatch:
      
jobs:
  call-aws-terraform-noinfranchange:
    uses: tikenek/github_actions/.github/workflows/terraform-template.yml@v1
    secrets:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      
      
      
name: reuse

on:
  workflow_dispatch:
  
jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: test reusable workflow
        uses: tikenek/github_actions/.github/workflows/terraform-template.yml@v1
        secrets:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}       

      
